### ISSUE TITLE
Support loading surveys from yaml

### ISSUE THREAD

**Issue by theodesp** [AlecAivazis/survey#154]
It would be nice if we could load surveys from yaml. For example:

```
survey:
  - question:
    name: name
    prompt:
      - input: "What is your name?"
    validate: required
    transform: title
  - question:
    name: color
    prompt:
      select:
        message: "Choose a color:"
        options: ["red", "blue", "green"]
        default: "red"
```

Then use a loader to bind them to a questions struct:

```
func main() {
    qs ,err: LoadFromYaml(somePath)
    if err != nil {
      log.Fatal(err);
    }
    // the answers will be written to this struct
    answers := struct {
        Name          string                  // survey will match the question and field names
        FavoriteColor string `survey:"color"` // or you can tag fields to match a specific name
        Age           int                     // if the types don't match exactly, survey will try to convert for you
    }{}

    // perform the questions
    err := survey.Ask(qs, &answers)
    if err != nil {
        fmt.Println(err.Error())
        return
    }

    fmt.Printf("%s chose %s.", answers.Name, answers.FavoriteColor)
}
